In [11]:
import numpy as np

### Random matrix generation

We need matrix of our quadratic function to be positive definite. The definition is: 

$$ M \text { positive definite } \Longleftrightarrow x^{\top} M x>0 \text { for all } x \in \mathbb{R}^{n} \backslash \mathbf{0} $$

And we know that matrix is p.d. if and only if all of it's eigenvalues are positive. So i have a little function that check if matrix is p.d. Actually we don't really need this, becouse if we create our matrix as $A=A*A^T$ we will definitely get symmetric and p.d. matrix (1-st is obvious, 2-nd is becouse <a href="https://en.wikipedia.org/wiki/Cholesky_decomposition">Cholesky decomposition</a>)

In [12]:
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

In [13]:
n = 3 # size 

A = np.random.rand(n, n)
A = A@A.T

while not is_pos_def(A):
    A = np.random.rand(n, n)
    A = A@A.T
b = np.random.rand(n, 1)

eps = 1e-6 # precision 

In [14]:
print(A)
print(b)

[[0.85289924 0.76734277 0.81831045]
 [0.76734277 0.9050484  0.7206928 ]
 [0.81831045 0.7206928  1.14945543]]
[[0.01281577]
 [0.86473599]
 [0.65472843]]


$$f(x)=\frac{1}{2} x^{T} A x+x^{T} b$$

We need result to be scalar, but numpy will give as array. So we use np.asscalar

In [15]:
def f(x):
    return np.asscalar(1/2*x.T@A@x + b.T@x)

### Steepest gradient descent

The theory behind this is simple. Let imagine that we have $x^k$ and we want to build $x^{k+1}$ that $f(x^{k+1}) < f(x^k)$. Let $x^{k+1} = x^k+\mu q$. So $q$ is direction, $\mu$ is step size. We can use condition on global minimum to find $\mu$. For our simple and convinient function it sounds like: $\dot{f}(x)=0$. So 
$$\begin{aligned} f\left(x^{k+1}\right) &=f\left(x^{k}+\mu q\right) \equiv \varphi(\mu)=\varphi(0)+\mu \dot{\varphi}(0)+\frac{1}{2} \mu^{2} \ddot{\varphi}(0), \quad \dot{\varphi}=\frac{d \varphi}{d \mu} \end{aligned}$$
Where 
$$\varphi(0)=f\left(x^{k}\right), \dot{\varphi}(0)=q^{T}\left(A x^{k}+b\right), \ddot{\varphi}(0)=q^{T} A q$$
And finally 
$$\bar{\mu}_{k}=-\frac{\dot{\varphi}(0)}{\ddot{\varphi}(0)}=-\frac{q^{T}\left(A x^{k}+b\right)}{q^{T} \cdot A q}$$

We build our ${x^{k+1}}$ using this formulas and get decreasing sequence for $f(x)$. And eventually we get our extrema 

The only thing left is direction of descent. And this is the only part that differ Gradient descent and Coordinate descent. 

In sgd we can take gradient of our function ($\operatorname{grad} f(x)=\left(\frac{\partial f(x)}{\partial x_{1}}, \frac{\partial f(x)}{\partial x_{2}}, \dots \frac{\partial f(x)}{\partial x_{n}}\right)^{T}$), in our case it would be $q=\operatorname{grad} f(x)=A x+b$

In cd we can take $q=e^{i}=(\underbrace{0,0, \ldots, 0,1}_{i}, 0 \ldots, 0)^{T}$ where $e^i$ - i-th unit vector in our vector space

In [16]:
def sgd():
    x = b # init approximation 
    i = 0 # count 

    while True:
        q = A@x + b # grad 

        mu = q.T @ q / (q.T @ A @ q)

        x_old = x
        x = x - np.asscalar(mu) * q

        i += 1
        if((np.linalg.norm(x - x_old) < eps and np.linalg.norm(q) < eps) or i > 1000000):
            break
    return x, i

In [17]:
x_sd, i_sd = sgd()

In [18]:
x_sd, i_sd

(array([[ 5.54689878],
        [-4.11457399],
        [-1.93871786]]), 57)

In [19]:
f(x_sd)

-2.3781336140781653

### Coordinate descent

E - is utility matrix that allow us to extract unit vectors from it

In [20]:
E = np.eye(n) 
E = np.matrix(E)

In [43]:
def cd():
    x = b
    i = 0

    while True: 
        for j in range(n):
            q = E[j].T
            mu = q.T @ (A[j]+ b)[j] / A[j][j]
            
            x_old = x
            x = x - np.asscalar(mu) * q
            print(x)
        i += 1
        if((np.linalg.norm(x - x_old) < eps and np.linalg.norm(A@x+b) < eps) or i > 1000000):
            break
    return x, i

In [44]:
x_coord, i_coord = cd()

[[-1.00221035]
 [ 0.86473599]
 [ 0.65472843]]
[[-1.00221035]
 [-1.0907223 ]
 [ 0.65472843]]
[[-1.00221035]
 [-1.0907223 ]
 [-0.91487037]]
[[-2.01723648]
 [-1.0907223 ]
 [-0.91487037]]
[[-2.01723648]
 [-3.04618058]
 [-0.91487037]]
[[-2.01723648]
 [-3.04618058]
 [-2.48446917]]
[[-3.03226261]
 [-3.04618058]
 [-2.48446917]]
[[-3.03226261]
 [-5.00163887]
 [-2.48446917]]
[[-3.03226261]
 [-5.00163887]
 [-4.05406797]]
[[-4.04728874]
 [-5.00163887]
 [-4.05406797]]
[[-4.04728874]
 [-6.95709716]
 [-4.05406797]]
[[-4.04728874]
 [-6.95709716]
 [-5.62366677]]
[[-5.06231487]
 [-6.95709716]
 [-5.62366677]]
[[-5.06231487]
 [-8.91255545]
 [-5.62366677]]
[[-5.06231487]
 [-8.91255545]
 [-7.19326556]]
[[-6.07734099]
 [-8.91255545]
 [-7.19326556]]
[[ -6.07734099]
 [-10.86801374]
 [ -7.19326556]]
[[ -6.07734099]
 [-10.86801374]
 [ -8.76286436]]
[[ -7.09236712]
 [-10.86801374]
 [ -8.76286436]]
[[ -7.09236712]
 [-12.82347203]
 [ -8.76286436]]
[[ -7.09236712]
 [-12.82347203]
 [-10.33246316]]
[[ -8.10739325]
 [-

[[-254.75874235]
 [-487.99983604]
 [-391.74497141]]
[[-254.75874235]
 [-489.95529433]
 [-391.74497141]]
[[-254.75874235]
 [-489.95529433]
 [-393.31457021]]
[[-255.77376848]
 [-489.95529433]
 [-393.31457021]]
[[-255.77376848]
 [-491.91075262]
 [-393.31457021]]
[[-255.77376848]
 [-491.91075262]
 [-394.88416901]]
[[-256.78879461]
 [-491.91075262]
 [-394.88416901]]
[[-256.78879461]
 [-493.86621091]
 [-394.88416901]]
[[-256.78879461]
 [-493.86621091]
 [-396.45376781]]
[[-257.80382073]
 [-493.86621091]
 [-396.45376781]]
[[-257.80382073]
 [-495.82166919]
 [-396.45376781]]
[[-257.80382073]
 [-495.82166919]
 [-398.02336661]]
[[-258.81884686]
 [-495.82166919]
 [-398.02336661]]
[[-258.81884686]
 [-497.77712748]
 [-398.02336661]]
[[-258.81884686]
 [-497.77712748]
 [-399.59296541]]
[[-259.83387299]
 [-497.77712748]
 [-399.59296541]]
[[-259.83387299]
 [-499.73258577]
 [-399.59296541]]
[[-259.83387299]
 [-499.73258577]
 [-401.16256421]]
[[-260.84889912]
 [-499.73258577]
 [-401.16256421]]
[[-260.84889

[[-455.73391569]
 [-877.13603538]
 [-704.09513249]]
[[-456.74894182]
 [-877.13603538]
 [-704.09513249]]
[[-456.74894182]
 [-879.09149367]
 [-704.09513249]]
[[-456.74894182]
 [-879.09149367]
 [-705.66473129]]
[[-457.76396795]
 [-879.09149367]
 [-705.66473129]]
[[-457.76396795]
 [-881.04695196]
 [-705.66473129]]
[[-457.76396795]
 [-881.04695196]
 [-707.23433009]]
[[-458.77899408]
 [-881.04695196]
 [-707.23433009]]
[[-458.77899408]
 [-883.00241024]
 [-707.23433009]]
[[-458.77899408]
 [-883.00241024]
 [-708.80392889]]
[[-459.7940202 ]
 [-883.00241024]
 [-708.80392889]]
[[-459.7940202 ]
 [-884.95786853]
 [-708.80392889]]
[[-459.7940202 ]
 [-884.95786853]
 [-710.37352769]]
[[-460.80904633]
 [-884.95786853]
 [-710.37352769]]
[[-460.80904633]
 [-886.91332682]
 [-710.37352769]]
[[-460.80904633]
 [-886.91332682]
 [-711.94312649]]
[[-461.82407246]
 [-886.91332682]
 [-711.94312649]]
[[-461.82407246]
 [-888.86878511]
 [-711.94312649]]
[[-461.82407246]
 [-888.86878511]
 [-713.51272529]]
[[-462.83909

 [ -892.44698841]]
[[ -578.55207718]
 [-1111.79102996]
 [ -892.44698841]]
[[ -578.55207718]
 [-1113.74648824]
 [ -892.44698841]]
[[ -578.55207718]
 [-1113.74648824]
 [ -894.01658721]]
[[ -579.56710331]
 [-1113.74648824]
 [ -894.01658721]]
[[ -579.56710331]
 [-1115.70194653]
 [ -894.01658721]]
[[ -579.56710331]
 [-1115.70194653]
 [ -895.58618601]]
[[ -580.58212943]
 [-1115.70194653]
 [ -895.58618601]]
[[ -580.58212943]
 [-1117.65740482]
 [ -895.58618601]]
[[ -580.58212943]
 [-1117.65740482]
 [ -897.15578481]]
[[ -581.59715556]
 [-1117.65740482]
 [ -897.15578481]]
[[ -581.59715556]
 [-1119.61286311]
 [ -897.15578481]]
[[ -581.59715556]
 [-1119.61286311]
 [ -898.72538361]]
[[ -582.61218169]
 [-1119.61286311]
 [ -898.72538361]]
[[ -582.61218169]
 [-1121.5683214 ]
 [ -898.72538361]]
[[ -582.61218169]
 [-1121.5683214 ]
 [ -900.29498241]]
[[ -583.62720782]
 [-1121.5683214 ]
 [ -900.29498241]]
[[ -583.62720782]
 [-1123.52377969]
 [ -900.29498241]]
[[ -583.62720782]
 [-1123.52377969]
 [ -901.86

 [-1171.8355747 ]]
[[ -759.22672796]
 [-1461.81806353]
 [-1173.4051735 ]]
[[ -760.24175409]
 [-1461.81806353]
 [-1173.4051735 ]]
[[ -760.24175409]
 [-1463.77352182]
 [-1173.4051735 ]]
[[ -760.24175409]
 [-1463.77352182]
 [-1174.9747723 ]]
[[ -761.25678021]
 [-1463.77352182]
 [-1174.9747723 ]]
[[ -761.25678021]
 [-1465.72898011]
 [-1174.9747723 ]]
[[ -761.25678021]
 [-1465.72898011]
 [-1176.5443711 ]]
[[ -762.27180634]
 [-1465.72898011]
 [-1176.5443711 ]]
[[ -762.27180634]
 [-1467.6844384 ]
 [-1176.5443711 ]]
[[ -762.27180634]
 [-1467.6844384 ]
 [-1178.1139699 ]]
[[ -763.28683247]
 [-1467.6844384 ]
 [-1178.1139699 ]]
[[ -763.28683247]
 [-1469.63989668]
 [-1178.1139699 ]]
[[ -763.28683247]
 [-1469.63989668]
 [-1179.6835687 ]]
[[ -764.3018586 ]
 [-1469.63989668]
 [-1179.6835687 ]]
[[ -764.3018586 ]
 [-1471.59535497]
 [-1179.6835687 ]]
[[ -764.3018586 ]
 [-1471.59535497]
 [-1181.2531675 ]]
[[ -765.31688473]
 [-1471.59535497]
 [-1181.2531675 ]]
[[ -765.31688473]
 [-1473.55081326]
 [-1181.25

[[ -877.98478493]
 [-1690.60668324]
 [-1355.47863423]]
[[ -877.98478493]
 [-1690.60668324]
 [-1357.04823303]]
[[ -878.99981106]
 [-1690.60668324]
 [-1357.04823303]]
[[ -878.99981106]
 [-1692.56214153]
 [-1357.04823303]]
[[ -878.99981106]
 [-1692.56214153]
 [-1358.61783183]]
[[ -880.01483719]
 [-1692.56214153]
 [-1358.61783183]]
[[ -880.01483719]
 [-1694.51759982]
 [-1358.61783183]]
[[ -880.01483719]
 [-1694.51759982]
 [-1360.18743063]]
[[ -881.02986332]
 [-1694.51759982]
 [-1360.18743063]]
[[ -881.02986332]
 [-1696.47305811]
 [-1360.18743063]]
[[ -881.02986332]
 [-1696.47305811]
 [-1361.75702943]]
[[ -882.04488944]
 [-1696.47305811]
 [-1361.75702943]]
[[ -882.04488944]
 [-1698.4285164 ]
 [-1361.75702943]]
[[ -882.04488944]
 [-1698.4285164 ]
 [-1363.32662823]]
[[ -883.05991557]
 [-1698.4285164 ]
 [-1363.32662823]]
[[ -883.05991557]
 [-1700.38397468]
 [-1363.32662823]]
[[ -883.05991557]
 [-1700.38397468]
 [-1364.89622703]]
[[ -884.0749417 ]
 [-1700.38397468]
 [-1364.89622703]]
[[ -884.07

 [-1567.37447215]]
[[-1015.01331221]
 [-1954.59355214]
 [-1567.37447215]]
[[-1015.01331221]
 [-1954.59355214]
 [-1568.94407095]]
[[-1016.02833834]
 [-1954.59355214]
 [-1568.94407095]]
[[-1016.02833834]
 [-1956.54901043]
 [-1568.94407095]]
[[-1016.02833834]
 [-1956.54901043]
 [-1570.51366975]]
[[-1017.04336447]
 [-1956.54901043]
 [-1570.51366975]]
[[-1017.04336447]
 [-1958.50446872]
 [-1570.51366975]]
[[-1017.04336447]
 [-1958.50446872]
 [-1572.08326855]]
[[-1018.05839059]
 [-1958.50446872]
 [-1572.08326855]]
[[-1018.05839059]
 [-1960.45992701]
 [-1572.08326855]]
[[-1018.05839059]
 [-1960.45992701]
 [-1573.65286735]]
[[-1019.07341672]
 [-1960.45992701]
 [-1573.65286735]]
[[-1019.07341672]
 [-1962.41538529]
 [-1573.65286735]]
[[-1019.07341672]
 [-1962.41538529]
 [-1575.22246614]]
[[-1020.08844285]
 [-1962.41538529]
 [-1575.22246614]]
[[-1020.08844285]
 [-1964.37084358]
 [-1575.22246614]]
[[-1020.08844285]
 [-1964.37084358]
 [-1576.79206494]]
[[-1021.10346898]
 [-1964.37084358]
 [-1576.79

 [-1873.44623803]]
[[-1212.94340717]
 [-2335.90791833]
 [-1875.01583683]]
[[-1213.9584333 ]
 [-2335.90791833]
 [-1875.01583683]]
[[-1213.9584333 ]
 [-2337.86337662]
 [-1875.01583683]]
[[-1213.9584333 ]
 [-2337.86337662]
 [-1876.58543563]]
[[-1214.97345942]
 [-2337.86337662]
 [-1876.58543563]]
[[-1214.97345942]
 [-2339.8188349 ]
 [-1876.58543563]]
[[-1214.97345942]
 [-2339.8188349 ]
 [-1878.15503442]]
[[-1215.98848555]
 [-2339.8188349 ]
 [-1878.15503442]]
[[-1215.98848555]
 [-2341.77429319]
 [-1878.15503442]]
[[-1215.98848555]
 [-2341.77429319]
 [-1879.72463322]]
[[-1217.00351168]
 [-2341.77429319]
 [-1879.72463322]]
[[-1217.00351168]
 [-2343.72975148]
 [-1879.72463322]]
[[-1217.00351168]
 [-2343.72975148]
 [-1881.29423202]]
[[-1218.01853781]
 [-2343.72975148]
 [-1881.29423202]]
[[-1218.01853781]
 [-2345.68520977]
 [-1881.29423202]]
[[-1218.01853781]
 [-2345.68520977]
 [-1882.86383082]]
[[-1219.03356394]
 [-2345.68520977]
 [-1882.86383082]]
[[-1219.03356394]
 [-2347.64066806]
 [-1882.86

[[-1352.0019867 ]
 [-2601.85024551]
 [-2088.48127354]]
[[-1352.0019867 ]
 [-2603.8057038 ]
 [-2088.48127354]]
[[-1352.0019867 ]
 [-2603.8057038 ]
 [-2090.05087234]]
[[-1353.01701283]
 [-2603.8057038 ]
 [-2090.05087234]]
[[-1353.01701283]
 [-2605.76116209]
 [-2090.05087234]]
[[-1353.01701283]
 [-2605.76116209]
 [-2091.62047114]]
[[-1354.03203896]
 [-2605.76116209]
 [-2091.62047114]]
[[-1354.03203896]
 [-2607.71662038]
 [-2091.62047114]]
[[-1354.03203896]
 [-2607.71662038]
 [-2093.19006994]]
[[-1355.04706509]
 [-2607.71662038]
 [-2093.19006994]]
[[-1355.04706509]
 [-2609.67207867]
 [-2093.19006994]]
[[-1355.04706509]
 [-2609.67207867]
 [-2094.75966874]]
[[-1356.06209121]
 [-2609.67207867]
 [-2094.75966874]]
[[-1356.06209121]
 [-2611.62753695]
 [-2094.75966874]]
[[-1356.06209121]
 [-2611.62753695]
 [-2096.32926754]]
[[-1357.07711734]
 [-2611.62753695]
 [-2096.32926754]]
[[-1357.07711734]
 [-2613.58299524]
 [-2096.32926754]]
[[-1357.07711734]
 [-2613.58299524]
 [-2097.89886634]]
[[-1358.09

 [-2272.12433307]]
[[-1470.76004368]
 [-2830.63886523]
 [-2272.12433307]]
[[-1470.76004368]
 [-2832.59432351]
 [-2272.12433307]]
[[-1470.76004368]
 [-2832.59432351]
 [-2273.69393187]]
[[-1471.7750698 ]
 [-2832.59432351]
 [-2273.69393187]]
[[-1471.7750698 ]
 [-2834.5497818 ]
 [-2273.69393187]]
[[-1471.7750698 ]
 [-2834.5497818 ]
 [-2275.26353067]]
[[-1472.79009593]
 [-2834.5497818 ]
 [-2275.26353067]]
[[-1472.79009593]
 [-2836.50524009]
 [-2275.26353067]]
[[-1472.79009593]
 [-2836.50524009]
 [-2276.83312947]]
[[-1473.80512206]
 [-2836.50524009]
 [-2276.83312947]]
[[-1473.80512206]
 [-2838.46069838]
 [-2276.83312947]]
[[-1473.80512206]
 [-2838.46069838]
 [-2278.40272827]]
[[-1474.82014819]
 [-2838.46069838]
 [-2278.40272827]]
[[-1474.82014819]
 [-2840.41615667]
 [-2278.40272827]]
[[-1474.82014819]
 [-2840.41615667]
 [-2279.97232707]]
[[-1475.83517432]
 [-2840.41615667]
 [-2279.97232707]]
[[-1475.83517432]
 [-2842.37161495]
 [-2279.97232707]]
[[-1475.83517432]
 [-2842.37161495]
 [-2281.54

 [-2661.38483532]]
[[-1722.48652342]
 [-3317.54797897]
 [-2662.95443411]]
[[-1723.50154954]
 [-3317.54797897]
 [-2662.95443411]]
[[-1723.50154954]
 [-3319.50343726]
 [-2662.95443411]]
[[-1723.50154954]
 [-3319.50343726]
 [-2664.52403291]]
[[-1724.51657567]
 [-3319.50343726]
 [-2664.52403291]]
[[-1724.51657567]
 [-3321.45889555]
 [-2664.52403291]]
[[-1724.51657567]
 [-3321.45889555]
 [-2666.09363171]]
[[-1725.5316018 ]
 [-3321.45889555]
 [-2666.09363171]]
[[-1725.5316018 ]
 [-3323.41435384]
 [-2666.09363171]]
[[-1725.5316018 ]
 [-3323.41435384]
 [-2667.66323051]]
[[-1726.54662793]
 [-3323.41435384]
 [-2667.66323051]]
[[-1726.54662793]
 [-3325.36981212]
 [-2667.66323051]]
[[-1726.54662793]
 [-3325.36981212]
 [-2669.23282931]]
[[-1727.56165406]
 [-3325.36981212]
 [-2669.23282931]]
[[-1727.56165406]
 [-3327.32527041]
 [-2669.23282931]]
[[-1727.56165406]
 [-3327.32527041]
 [-2670.80242811]]
[[-1728.57668018]
 [-3327.32527041]
 [-2670.80242811]]
[[-1728.57668018]
 [-3329.2807287 ]
 [-2670.80

 [-2967.45660119]]
[[-1920.41661837]
 [-3698.86234516]
 [-2969.02619999]]
[[-1921.4316445 ]
 [-3698.86234516]
 [-2969.02619999]]
[[-1921.4316445 ]
 [-3700.81780344]
 [-2969.02619999]]
[[-1921.4316445 ]
 [-3700.81780344]
 [-2970.59579879]]
[[-1922.44667063]
 [-3700.81780344]
 [-2970.59579879]]
[[-1922.44667063]
 [-3702.77326173]
 [-2970.59579879]]
[[-1922.44667063]
 [-3702.77326173]
 [-2972.16539759]]
[[-1923.46169676]
 [-3702.77326173]
 [-2972.16539759]]
[[-1923.46169676]
 [-3704.72872002]
 [-2972.16539759]]
[[-1923.46169676]
 [-3704.72872002]
 [-2973.73499639]]
[[-1924.47672288]
 [-3704.72872002]
 [-2973.73499639]]
[[-1924.47672288]
 [-3706.68417831]
 [-2973.73499639]]
[[-1924.47672288]
 [-3706.68417831]
 [-2975.30459519]]
[[-1925.49174901]
 [-3706.68417831]
 [-2975.30459519]]
[[-1925.49174901]
 [-3708.6396366 ]
 [-2975.30459519]]
[[-1925.49174901]
 [-3708.6396366 ]
 [-2976.87419399]]
[[-1926.50677514]
 [-3708.6396366 ]
 [-2976.87419399]]
[[-1926.50677514]
 [-3710.59509489]
 [-2976.87

 [-3074.18931955]]
[[-1989.43839508]
 [-3831.83350875]
 [-3074.18931955]]
[[-1989.43839508]
 [-3831.83350875]
 [-3075.75891835]]
[[-1990.4534212 ]
 [-3831.83350875]
 [-3075.75891835]]
[[-1990.4534212 ]
 [-3833.78896704]
 [-3075.75891835]]
[[-1990.4534212 ]
 [-3833.78896704]
 [-3077.32851715]]
[[-1991.46844733]
 [-3833.78896704]
 [-3077.32851715]]
[[-1991.46844733]
 [-3835.74442533]
 [-3077.32851715]]
[[-1991.46844733]
 [-3835.74442533]
 [-3078.89811595]]
[[-1992.48347346]
 [-3835.74442533]
 [-3078.89811595]]
[[-1992.48347346]
 [-3837.69988361]
 [-3078.89811595]]
[[-1992.48347346]
 [-3837.69988361]
 [-3080.46771475]]
[[-1993.49849959]
 [-3837.69988361]
 [-3080.46771475]]
[[-1993.49849959]
 [-3839.6553419 ]
 [-3080.46771475]]
[[-1993.49849959]
 [-3839.6553419 ]
 [-3082.03731355]]
[[-1994.51352572]
 [-3839.6553419 ]
 [-3082.03731355]]
[[-1994.51352572]
 [-3841.61080019]
 [-3082.03731355]]
[[-1994.51352572]
 [-3841.61080019]
 [-3083.60691235]]
[[-1995.52855184]
 [-3841.61080019]
 [-3083.60

 [-3366.13469624]]
[[-2178.23325488]
 [-4195.54875034]
 [-3366.13469624]]
[[-2178.23325488]
 [-4195.54875034]
 [-3367.70429504]]
[[-2179.24828101]
 [-4195.54875034]
 [-3367.70429504]]
[[-2179.24828101]
 [-4197.50420863]
 [-3367.70429504]]
[[-2179.24828101]
 [-4197.50420863]
 [-3369.27389384]]
[[-2180.26330714]
 [-4197.50420863]
 [-3369.27389384]]
[[-2180.26330714]
 [-4199.45966692]
 [-3369.27389384]]
[[-2180.26330714]
 [-4199.45966692]
 [-3370.84349263]]
[[-2181.27833326]
 [-4199.45966692]
 [-3370.84349263]]
[[-2181.27833326]
 [-4201.41512521]
 [-3370.84349263]]
[[-2181.27833326]
 [-4201.41512521]
 [-3372.41309143]]
[[-2182.29335939]
 [-4201.41512521]
 [-3372.41309143]]
[[-2182.29335939]
 [-4203.3705835 ]
 [-3372.41309143]]
[[-2182.29335939]
 [-4203.3705835 ]
 [-3373.98269023]]
[[-2183.30838552]
 [-4203.3705835 ]
 [-3373.98269023]]
[[-2183.30838552]
 [-4205.32604178]
 [-3373.98269023]]
[[-2183.30838552]
 [-4205.32604178]
 [-3375.55228903]]
[[-2184.32341165]
 [-4205.32604178]
 [-3375.55

[[-2361.95298405]
 [-4547.53124221]
 [-3650.23207892]]
[[-2361.95298405]
 [-4549.48670049]
 [-3650.23207892]]
[[-2361.95298405]
 [-4549.48670049]
 [-3651.80167772]]
[[-2362.96801017]
 [-4549.48670049]
 [-3651.80167772]]
[[-2362.96801017]
 [-4551.44215878]
 [-3651.80167772]]
[[-2362.96801017]
 [-4551.44215878]
 [-3653.37127652]]
[[-2363.9830363 ]
 [-4551.44215878]
 [-3653.37127652]]
[[-2363.9830363 ]
 [-4553.39761707]
 [-3653.37127652]]
[[-2363.9830363 ]
 [-4553.39761707]
 [-3654.94087532]]
[[-2364.99806243]
 [-4553.39761707]
 [-3654.94087532]]
[[-2364.99806243]
 [-4555.35307536]
 [-3654.94087532]]
[[-2364.99806243]
 [-4555.35307536]
 [-3656.51047412]]
[[-2366.01308856]
 [-4555.35307536]
 [-3656.51047412]]
[[-2366.01308856]
 [-4557.30853365]
 [-3656.51047412]]
[[-2366.01308856]
 [-4557.30853365]
 [-3658.08007292]]
[[-2367.02811469]
 [-4557.30853365]
 [-3658.08007292]]
[[-2367.02811469]
 [-4559.26399194]
 [-3658.08007292]]
[[-2367.02811469]
 [-4559.26399194]
 [-3659.64967172]]
[[-2368.04

 [-3929.62066521]]
[[-2542.62763483]
 [-4897.55827578]
 [-3929.62066521]]
[[-2542.62763483]
 [-4897.55827578]
 [-3931.19026401]]
[[-2543.64266095]
 [-4897.55827578]
 [-3931.19026401]]
[[-2543.64266095]
 [-4899.51373407]
 [-3931.19026401]]
[[-2543.64266095]
 [-4899.51373407]
 [-3932.75986281]]
[[-2544.65768708]
 [-4899.51373407]
 [-3932.75986281]]
[[-2544.65768708]
 [-4901.46919236]
 [-3932.75986281]]
[[-2544.65768708]
 [-4901.46919236]
 [-3934.32946161]]
[[-2545.67271321]
 [-4901.46919236]
 [-3934.32946161]]
[[-2545.67271321]
 [-4903.42465065]
 [-3934.32946161]]
[[-2545.67271321]
 [-4903.42465065]
 [-3935.89906041]]
[[-2546.68773934]
 [-4903.42465065]
 [-3935.89906041]]
[[-2546.68773934]
 [-4905.38010893]
 [-3935.89906041]]
[[-2546.68773934]
 [-4905.38010893]
 [-3937.46865921]]
[[-2547.70276547]
 [-4905.38010893]
 [-3937.46865921]]
[[-2547.70276547]
 [-4907.33556722]
 [-3937.46865921]]
[[-2547.70276547]
 [-4907.33556722]
 [-3939.03825801]]
[[-2548.71779159]
 [-4907.33556722]
 [-3939.03

 [-4230.98363469]]
[[-2737.5126514 ]
 [-5271.05080882]
 [-4230.98363469]]
[[-2737.5126514 ]
 [-5273.0062671 ]
 [-4230.98363469]]
[[-2737.5126514 ]
 [-5273.0062671 ]
 [-4232.55323349]]
[[-2738.52767753]
 [-5273.0062671 ]
 [-4232.55323349]]
[[-2738.52767753]
 [-5274.96172539]
 [-4232.55323349]]
[[-2738.52767753]
 [-5274.96172539]
 [-4234.12283229]]
[[-2739.54270366]
 [-5274.96172539]
 [-4234.12283229]]
[[-2739.54270366]
 [-5276.91718368]
 [-4234.12283229]]
[[-2739.54270366]
 [-5276.91718368]
 [-4235.69243109]]
[[-2740.55772978]
 [-5276.91718368]
 [-4235.69243109]]
[[-2740.55772978]
 [-5278.87264197]
 [-4235.69243109]]
[[-2740.55772978]
 [-5278.87264197]
 [-4237.26202989]]
[[-2741.57275591]
 [-5278.87264197]
 [-4237.26202989]]
[[-2741.57275591]
 [-5280.82810026]
 [-4237.26202989]]
[[-2741.57275591]
 [-5280.82810026]
 [-4238.83162869]]
[[-2742.58778204]
 [-5280.82810026]
 [-4238.83162869]]
[[-2742.58778204]
 [-5282.78355854]
 [-4238.83162869]]
[[-2742.58778204]
 [-5282.78355854]
 [-4240.40

 [-4505.66342459]]
[[-2915.1422238 ]
 [-5615.21146753]
 [-4505.66342459]]
[[-2915.1422238 ]
 [-5615.21146753]
 [-4507.23302339]]
[[-2916.15724992]
 [-5615.21146753]
 [-4507.23302339]]
[[-2916.15724992]
 [-5617.16692582]
 [-4507.23302339]]
[[-2916.15724992]
 [-5617.16692582]
 [-4508.80262218]]
[[-2917.17227605]
 [-5617.16692582]
 [-4508.80262218]]
[[-2917.17227605]
 [-5619.1223841 ]
 [-4508.80262218]]
[[-2917.17227605]
 [-5619.1223841 ]
 [-4510.37222098]]
[[-2918.18730218]
 [-5619.1223841 ]
 [-4510.37222098]]
[[-2918.18730218]
 [-5621.07784239]
 [-4510.37222098]]
[[-2918.18730218]
 [-5621.07784239]
 [-4511.94181978]]
[[-2919.20232831]
 [-5621.07784239]
 [-4511.94181978]]
[[-2919.20232831]
 [-5623.03330068]
 [-4511.94181978]]
[[-2919.20232831]
 [-5623.03330068]
 [-4513.51141858]]
[[-2920.21735444]
 [-5623.03330068]
 [-4513.51141858]]
[[-2920.21735444]
 [-5624.98875897]
 [-4513.51141858]]
[[-2920.21735444]
 [-5624.98875897]
 [-4515.08101738]]
[[-2921.23238056]
 [-5624.98875897]
 [-4515.08

 [-4808.59599287]]
[[-3111.0422665 ]
 [-5992.61491714]
 [-4810.16559167]]
[[-3112.05729263]
 [-5992.61491714]
 [-4810.16559167]]
[[-3112.05729263]
 [-5994.57037542]
 [-4810.16559167]]
[[-3112.05729263]
 [-5994.57037542]
 [-4811.73519047]]
[[-3113.07231875]
 [-5994.57037542]
 [-4811.73519047]]
[[-3113.07231875]
 [-5996.52583371]
 [-4811.73519047]]
[[-3113.07231875]
 [-5996.52583371]
 [-4813.30478926]]
[[-3114.08734488]
 [-5996.52583371]
 [-4813.30478926]]
[[-3114.08734488]
 [-5998.481292  ]
 [-4813.30478926]]
[[-3114.08734488]
 [-5998.481292  ]
 [-4814.87438806]]
[[-3115.10237101]
 [-5998.481292  ]
 [-4814.87438806]]
[[-3115.10237101]
 [-6000.43675029]
 [-4814.87438806]]
[[-3115.10237101]
 [-6000.43675029]
 [-4816.44398686]]
[[-3116.11739714]
 [-6000.43675029]
 [-4816.44398686]]
[[-3116.11739714]
 [-6002.39220858]
 [-4816.44398686]]
[[-3116.11739714]
 [-6002.39220858]
 [-4818.01358566]]
[[-3117.13242327]
 [-6002.39220858]
 [-4818.01358566]]
[[-3117.13242327]
 [-6004.34766687]
 [-4818.01

[[-3311.00241371]
 [-6377.8401999 ]
 [-5117.80695634]]
[[-3311.00241371]
 [-6377.8401999 ]
 [-5119.37655514]]
[[-3312.01743984]
 [-6377.8401999 ]
 [-5119.37655514]]
[[-3312.01743984]
 [-6379.79565819]
 [-5119.37655514]]
[[-3312.01743984]
 [-6379.79565819]
 [-5120.94615394]]
[[-3313.03246597]
 [-6379.79565819]
 [-5120.94615394]]
[[-3313.03246597]
 [-6381.75111648]
 [-5120.94615394]]
[[-3313.03246597]
 [-6381.75111648]
 [-5122.51575274]]
[[-3314.04749209]
 [-6381.75111648]
 [-5122.51575274]]
[[-3314.04749209]
 [-6383.70657476]
 [-5122.51575274]]
[[-3314.04749209]
 [-6383.70657476]
 [-5124.08535154]]
[[-3315.06251822]
 [-6383.70657476]
 [-5124.08535154]]
[[-3315.06251822]
 [-6385.66203305]
 [-5124.08535154]]
[[-3315.06251822]
 [-6385.66203305]
 [-5125.65495034]]
[[-3316.07754435]
 [-6385.66203305]
 [-5125.65495034]]
[[-3316.07754435]
 [-6387.61749134]
 [-5125.65495034]]
[[-3316.07754435]
 [-6387.61749134]
 [-5127.22454914]]
[[-3317.09257048]
 [-6387.61749134]
 [-5127.22454914]]
[[-3317.09

 [-5470.9666862 ]]
[[-3539.38329251]
 [-6815.86285644]
 [-5470.9666862 ]]
[[-3539.38329251]
 [-6817.81831473]
 [-5470.9666862 ]]
[[-3539.38329251]
 [-6817.81831473]
 [-5472.536285  ]]
[[-3540.39831863]
 [-6817.81831473]
 [-5472.536285  ]]
[[-3540.39831863]
 [-6819.77377302]
 [-5472.536285  ]]
[[-3540.39831863]
 [-6819.77377302]
 [-5474.1058838 ]]
[[-3541.41334476]
 [-6819.77377302]
 [-5474.1058838 ]]
[[-3541.41334476]
 [-6821.72923131]
 [-5474.1058838 ]]
[[-3541.41334476]
 [-6821.72923131]
 [-5475.6754826 ]]
[[-3542.42837089]
 [-6821.72923131]
 [-5475.6754826 ]]
[[-3542.42837089]
 [-6823.68468959]
 [-5475.6754826 ]]
[[-3542.42837089]
 [-6823.68468959]
 [-5477.2450814 ]]
[[-3543.44339702]
 [-6823.68468959]
 [-5477.2450814 ]]
[[-3543.44339702]
 [-6825.64014788]
 [-5477.2450814 ]]
[[-3543.44339702]
 [-6825.64014788]
 [-5478.8146802 ]]
[[-3544.45842315]
 [-6825.64014788]
 [-5478.8146802 ]]
[[-3544.45842315]
 [-6827.59560617]
 [-5478.8146802 ]]
[[-3544.45842315]
 [-6827.59560617]
 [-5480.38

[[-3738.32841359]
 [-7201.0881392 ]
 [-5780.17764968]]
[[-3739.34343972]
 [-7201.0881392 ]
 [-5780.17764968]]
[[-3739.34343972]
 [-7203.04359749]
 [-5780.17764968]]
[[-3739.34343972]
 [-7203.04359749]
 [-5781.74724848]]
[[-3740.35846585]
 [-7203.04359749]
 [-5781.74724848]]
[[-3740.35846585]
 [-7204.99905578]
 [-5781.74724848]]
[[-3740.35846585]
 [-7204.99905578]
 [-5783.31684728]]
[[-3741.37349198]
 [-7204.99905578]
 [-5783.31684728]]
[[-3741.37349198]
 [-7206.95451407]
 [-5783.31684728]]
[[-3741.37349198]
 [-7206.95451407]
 [-5784.88644608]]
[[-3742.3885181 ]
 [-7206.95451407]
 [-5784.88644608]]
[[-3742.3885181 ]
 [-7208.90997236]
 [-5784.88644608]]
[[-3742.3885181 ]
 [-7208.90997236]
 [-5786.45604488]]
[[-3743.40354423]
 [-7208.90997236]
 [-5786.45604488]]
[[-3743.40354423]
 [-7210.86543064]
 [-5786.45604488]]
[[-3743.40354423]
 [-7210.86543064]
 [-5788.02564368]]
[[-3744.41857036]
 [-7210.86543064]
 [-5788.02564368]]
[[-3744.41857036]
 [-7212.82088893]
 [-5788.02564368]]
[[-3744.41

 [-6059.56623597]]
[[-3920.0180905 ]
 [-7551.11517278]
 [-6061.13583477]]
[[-3921.03311663]
 [-7551.11517278]
 [-6061.13583477]]
[[-3921.03311663]
 [-7553.07063107]
 [-6061.13583477]]
[[-3921.03311663]
 [-7553.07063107]
 [-6062.70543357]]
[[-3922.04814276]
 [-7553.07063107]
 [-6062.70543357]]
[[-3922.04814276]
 [-7555.02608935]
 [-6062.70543357]]
[[-3922.04814276]
 [-7555.02608935]
 [-6064.27503237]]
[[-3923.06316888]
 [-7555.02608935]
 [-6064.27503237]]
[[-3923.06316888]
 [-7556.98154764]
 [-6064.27503237]]
[[-3923.06316888]
 [-7556.98154764]
 [-6065.84463117]]
[[-3924.07819501]
 [-7556.98154764]
 [-6065.84463117]]
[[-3924.07819501]
 [-7558.93700593]
 [-6065.84463117]]
[[-3924.07819501]
 [-7558.93700593]
 [-6067.41422997]]
[[-3925.09322114]
 [-7558.93700593]
 [-6067.41422997]]
[[-3925.09322114]
 [-7560.89246422]
 [-6067.41422997]]
[[-3925.09322114]
 [-7560.89246422]
 [-6068.98382877]]
[[-3926.10824727]
 [-7560.89246422]
 [-6068.98382877]]
[[-3926.10824727]
 [-7562.84792251]
 [-6068.98

[[-4089.52745387]
 [-7875.72124861]
 [-6321.68923547]]
[[-4089.52745387]
 [-7877.6767069 ]
 [-6321.68923547]]
[[-4089.52745387]
 [-7877.6767069 ]
 [-6323.25883427]]
[[-4090.54248   ]
 [-7877.6767069 ]
 [-6323.25883427]]
[[-4090.54248   ]
 [-7879.63216518]
 [-6323.25883427]]
[[-4090.54248   ]
 [-7879.63216518]
 [-6324.82843307]]
[[-4091.55750613]
 [-7879.63216518]
 [-6324.82843307]]
[[-4091.55750613]
 [-7881.58762347]
 [-6324.82843307]]
[[-4091.55750613]
 [-7881.58762347]
 [-6326.39803187]]
[[-4092.57253226]
 [-7881.58762347]
 [-6326.39803187]]
[[-4092.57253226]
 [-7883.54308176]
 [-6326.39803187]]
[[-4092.57253226]
 [-7883.54308176]
 [-6327.96763067]]
[[-4093.58755839]
 [-7883.54308176]
 [-6327.96763067]]
[[-4093.58755839]
 [-7885.49854005]
 [-6327.96763067]]
[[-4093.58755839]
 [-7885.49854005]
 [-6329.53722947]]
[[-4094.60258451]
 [-7885.49854005]
 [-6329.53722947]]
[[-4094.60258451]
 [-7887.45399834]
 [-6329.53722947]]
[[-4094.60258451]
 [-7887.45399834]
 [-6331.10682826]]
[[-4095.61

 [-6599.50822296]]
[[-4269.18707853]
 [-8223.7928239 ]
 [-6599.50822296]]
[[-4269.18707853]
 [-8223.7928239 ]
 [-6601.07782176]]
[[-4270.20210465]
 [-8223.7928239 ]
 [-6601.07782176]]
[[-4270.20210465]
 [-8225.74828218]
 [-6601.07782176]]
[[-4270.20210465]
 [-8225.74828218]
 [-6602.64742056]]
[[-4271.21713078]
 [-8225.74828218]
 [-6602.64742056]]
[[-4271.21713078]
 [-8227.70374047]
 [-6602.64742056]]
[[-4271.21713078]
 [-8227.70374047]
 [-6604.21701936]]
[[-4272.23215691]
 [-8227.70374047]
 [-6604.21701936]]
[[-4272.23215691]
 [-8229.65919876]
 [-6604.21701936]]
[[-4272.23215691]
 [-8229.65919876]
 [-6605.78661816]]
[[-4273.24718304]
 [-8229.65919876]
 [-6605.78661816]]
[[-4273.24718304]
 [-8231.61465705]
 [-6605.78661816]]
[[-4273.24718304]
 [-8231.61465705]
 [-6607.35621696]]
[[-4274.26220917]
 [-8231.61465705]
 [-6607.35621696]]
[[-4274.26220917]
 [-8233.57011534]
 [-6607.35621696]]
[[-4274.26220917]
 [-8233.57011534]
 [-6608.92581575]]
[[-4275.27723529]
 [-8233.57011534]
 [-6608.92

 [-6891.45359964]]
[[-4457.98193833]
 [-8585.5526072 ]
 [-6891.45359964]]
[[-4457.98193833]
 [-8587.50806549]
 [-6891.45359964]]
[[-4457.98193833]
 [-8587.50806549]
 [-6893.02319844]]
[[-4458.99696446]
 [-8587.50806549]
 [-6893.02319844]]
[[-4458.99696446]
 [-8589.46352378]
 [-6893.02319844]]
[[-4458.99696446]
 [-8589.46352378]
 [-6894.59279724]]
[[-4460.01199059]
 [-8589.46352378]
 [-6894.59279724]]
[[-4460.01199059]
 [-8591.41898207]
 [-6894.59279724]]
[[-4460.01199059]
 [-8591.41898207]
 [-6896.16239604]]
[[-4461.02701672]
 [-8591.41898207]
 [-6896.16239604]]
[[-4461.02701672]
 [-8593.37444035]
 [-6896.16239604]]
[[-4461.02701672]
 [-8593.37444035]
 [-6897.73199484]]
[[-4462.04204284]
 [-8593.37444035]
 [-6897.73199484]]
[[-4462.04204284]
 [-8595.32989864]
 [-6897.73199484]]
[[-4462.04204284]
 [-8595.32989864]
 [-6899.30159364]]
[[-4463.05706897]
 [-8595.32989864]
 [-6899.30159364]]
[[-4463.05706897]
 [-8597.28535693]
 [-6899.30159364]]
[[-4463.05706897]
 [-8597.28535693]
 [-6900.87

 [-7192.81656912]]
[[-4652.8669549 ]
 [-8961.00059852]
 [-7192.81656912]]
[[-4652.8669549 ]
 [-8962.95605681]
 [-7192.81656912]]
[[-4652.8669549 ]
 [-8962.95605681]
 [-7194.38616792]]
[[-4653.88198103]
 [-8962.95605681]
 [-7194.38616792]]
[[-4653.88198103]
 [-8964.9115151 ]
 [-7194.38616792]]
[[-4653.88198103]
 [-8964.9115151 ]
 [-7195.95576672]]
[[-4654.89700716]
 [-8964.9115151 ]
 [-7195.95576672]]
[[-4654.89700716]
 [-8966.86697339]
 [-7195.95576672]]
[[-4654.89700716]
 [-8966.86697339]
 [-7197.52536552]]
[[-4655.91203329]
 [-8966.86697339]
 [-7197.52536552]]
[[-4655.91203329]
 [-8968.82243168]
 [-7197.52536552]]
[[-4655.91203329]
 [-8968.82243168]
 [-7199.09496432]]
[[-4656.92705942]
 [-8968.82243168]
 [-7199.09496432]]
[[-4656.92705942]
 [-8970.77788996]
 [-7199.09496432]]
[[-4656.92705942]
 [-8970.77788996]
 [-7200.66456312]]
[[-4657.94208554]
 [-8970.77788996]
 [-7200.66456312]]
[[-4657.94208554]
 [-8972.73334825]
 [-7200.66456312]]
[[-4657.94208554]
 [-8972.73334825]
 [-7202.23

KeyboardInterrupt: 

In [32]:
x_coord, i_coord

(matrix([[ 5.54689096],
         [-4.11457168],
         [-1.93871252]]), 176)

In [24]:
f(x_coord)

-2.378133614071034

### Gaussian elimination

Well it is a well known algorithm in linear algebra for soloving systems of linear equations (<a href="https://en.wikipedia.org/wiki/Gaussian_elimination">link</a>)

In [25]:
def gaus(A, b):
    n = A.shape[0]
    for i in range(n):
        b[i] = b[i] / A[i][i]
        A[i] = A[i] / A[i][i]
        for j in range(i + 1, n):
            b[j] = b[j] - A[j][i] * b[i]
            A[j] = A[j] - A[j][i] * A[i]

    for i in range(n - 1, -1, -1):
        for j in range(i - 1, -1, -1):
            b[j] -= b[i] * A[j][i]
    return b

In [26]:
x_pr = gaus(A.copy(), -b.copy())

In [27]:
x_pr

array([[ 5.54690025],
       [-4.11457492],
       [-1.93871834]])

In [18]:
f(x_pr)

-6.574604400639203

### Comparison of methods

#### gradient descent

In [28]:
print("Discrepancy with the exact answer: ", np.linalg.norm(x_sd - x_pr))
print("number of steps: ", i_sd)

Discrepancy with the exact answer:  1.8084252710174648e-06
number of steps:  57


#### coordinate descent 

In [29]:
print("Discrepancy with the exact answer: ", np.linalg.norm(x_coord - x_pr))
print("number of steps: ", i_coord)

Discrepancy with the exact answer:  1.143296702358046e-05
number of steps:  176
